[project]
name = "mlh-pe-hackathon"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "faker>=33.0",
    "flask>=3.1",
    "flask-caching>=2.3",
    "gunicorn>=26.0.0",
    "peewee>=3.17",
    "psycopg2-binary>=2.9",
    "python-dotenv>=1.0",
    "redis>=5.0",
    "prometheus-flask-exporter>=0.23",
    "prometheus-client>=0.21",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-cov>=6.0",
    "locust>=2.31",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.coverage.run]
source = ["app"]
omit = ["app/models/__init__.py"]

[tool.coverage.report]
show_missing = true
skip_empty = true
fail_under = 98
