name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - run: uv sync --dev
      - run: uv run pytest || test $? -eq 5
